const ActionTypes = {
  // Auth user

  // Search
  SEARCH_REQUEST: 'SEARCH_REQUEST',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_FAILURE: 'SEARCH_FAILURE',

  // Fetch resource
  FETCH_RESOURCE_REQUEST: 'FETCH_RESOURCE_REQUEST',
  FETCH_RESOURCE_SUCCESS: 'FETCH_RESOURCE_SUCCESS',
  FETCH_RESOURCE_FAILURE: 'FETCH_RESOURCE_FAILURE',

  // Fetch resources
  FETCH_RESOURCES_REQUEST: 'FETCH_RESOURCES_REQUEST',
  FETCH_RESOURCES_SUCCESS: 'FETCH_RESOURCES_SUCCESS',
  FETCH_RESOURCES_FAILURE: 'FETCH_RESOURCES_FAILURE',

};

export default ActionTypes;
